name: Pull Request Pipeline
on: [pull_request]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sam Build ğŸ—ï¸
        run: sam build --use-container

      - name: Install dependencies ğŸ“¦
        working-directory: ./localize-serverless
        run: |
          npm ci
      - name: Lint the repository ğŸ”¬
        working-directory: ./localize-serverless
        run: |
          npm run lint:check
      - name: Run tests ğŸ§ª
        working-directory: ./localize-serverless
        run: |
          npm run test:ci
      - run: echo "Done ğŸ‰"

