name: Pull Request Pipeline
on: [pull_request]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code  ğŸ“¥
        uses: actions/checkout@v3
      - name: Setup node ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.x
          cache: npm
      - name: Install dependencies ğŸ“¦
        run: |
          npm ci
      - name: Lint the repository ğŸ”¬
        run: |
          npm run lint
      - name: Run tests ğŸ”¬
        run: |
          npm run test:coverage
      - run: echo "Done ğŸ‰"
